name: RPG
version: 1.4.1
author: matejkormuth
main: eu.matejkormuth.rpgdavid.RpgPlugin

commands: 
  party:
    description: Party command.
  playerhead:
    description: Gives you player head.
  character:
    description: Kills you and shows character select menu.
    aliases: [characters, suicide]
  'yes':
    description: Accepts offered quest.
    aliases: [jo, ano]
  'no':
    description: Declines offered quest.
    aliases: [ne, nie]
  money:
    description: Command used for giving money.
  setport:
    description: Command for setting port locations.
  warp:
    description: Teleports you to specified warp.
  setwarp:
    description: Creates new warp where are you standing.
  setspeed:
    description: Sets players's walking and flying speed.
  rp:
    description: Sets resource pack type.
  bt:
    description: Sets type of brush.
  bs:
    description: Sets size of brush.
  f:
    description: Sets filter.
  fp:
    description: Sets filter properties.
  ar:
    description: Applies current filter on WE region.
    