// This file is automatically generated.
// Changes to this file wont be perserved!
// Generated at: 3.4.2015 20:23
// Licensed under GPL-3.

package eu.matejkormuth.rpgdavid.starving.sounds.lists;

import eu.matejkormuth.rpgdavid.starving.sounds.Atmosphere;

public class Atmospheres { 
    private Atmospheres() {}
    public static final Atmosphere WOODS_CALM = new Atmosphere(Sounds.WOODS1, Sounds.WOODS2, Sounds.WOODS3);
}

