// This file is automatically generated.
// Changes to this file wont be perserved!
// Generated at: 1.2.2015 23:32
// Licensed under GPL-3.

package eu.matejkormuth.rpgdavid.starving.sounds.lists;

import eu.matejkormuth.rpgdavid.starving.sounds.Atmosphere;

public class Atmospheres { 
    public Atmospheres() {}
    public static final Atmosphere WOODS_CALM = new Atmosphere(Sounds.WOODS1, Sounds.WOODS2, Sounds.WOODS3);
}

