// This file is automatically generated.
// Changes to this file wont be perserved!
// Generated at: 2.2.2015 13:40
// Licensed under GPL-3.

package eu.matejkormuth.rpgdavid.starving.sounds.lists;

import eu.matejkormuth.rpgdavid.starving.sounds.NamedSound;

public class Sounds { 
    public Sounds() {}
    public static final NamedSound WOODS1 = new NamedSound("woods1", 5490);
    public static final NamedSound WOODS2 = new NamedSound("woods2", 5490);
    public static final NamedSound WOODS3 = new NamedSound("woods3", 5490);
}

